### ISSUE TITLE
Install fails in restricted environment due to an unusal dependency entry in the tree

### ISSUE THREAD

**Issue by sarimarton** [zmagyar/extjs-loader#6]
Hi,

I'd like to onboard this package in a restricted enterprise environment, but the onboarding process has been stuck due to the fact that one of the dependencies of this package attempts to make an outside request.

The problematic dependency is _esprima-ast-utils@0.0.6_ which has this dependency entry:
    `"esprima": "git://github.com/ariya/esprima.git#master"`

esprima-ast-utils@0.0.7 fixes this problem by using a normal semver definition:
    `"esprima": "^3.1.3"`

Is it possible to update the dependency _esprima-ast-utils@0.0.6_ to 0.0.7?

Thanks,
Marton

**Comment by zmagyar** [comment]
Fixed in [v0.0.10](https://github.com/zmagyar/extjs-loader/tree/v0.0.10)
