### ISSUE TITLE
compatibility with TypeScript

### ISSUE THREAD

**Issue by jhuss** [zmagyar/extjs-loader#8]
on an extjs app that I working is in typescript and webpack (using **ts-loader**)
adding the **extjs-loader** module, the app keep trying to load a **.js** files, inspecting the code at this line:

https://github.com/zmagyar/extjs-loader/blob/8f9fc17c8657eeeb9872bfc7820984aa703be089/lib/loader.js#L58

removing the `+ '.js'` string concatenated at the end is working, and app load correctly

**Comment by zmagyar** [comment]
That's only working if js is listed in in webpack config. Anyway if you make a PR I'm happy to merge.

**Comment by zmagyar** [comment]
Merged PR and published under v0.0.11
